### PR TITLE
For #25, paste several descriptions from USGS PDFs

### PR DESCRIPTION
**Pull request by brandon-rhodes**

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
There — I've added a pull request with the final Unknowns filled in (besides the spurious `Trm`). In one case where I saw `red` as the color, I filled in the yellow used in the PDF, except that the PDF has red dots too for that formation's rendering.

I have probably not been consistent in two respects:

* Sometimes I pulled in the whole title of the formation including its eras listed in parenthesis, as it was only as I was finishing the PR that I noticed the other formations don't seem to include those in their titles.
* I did not always scroll up and include the section heading (like "Moenkopi Formation") in the formation name, even though as I was finishing I noticed that this was a general practice across these descriptions.

But rather than fiddle further, I'm going to put my pencil down for the evening, and wait to see what comments you have. Then I can accomplish whatever tweaks you need all at once!

**Comment by rclark** [comment]
🙇 I'm so grateful for your work here @brandon-rhodes. This is really so helpful.

> ... from USGS PDFs

Did you use PDFs other than [the ones I've already listed here](https://github.com/rclark/grand-canyon-geology#grand-canyon-geology)? If so, do you mind adding additional bullets & links if you have them?

**Comment by brandon-rhodes** [comment]
> Did you use PDFs other than the ones I've already listed here?

Happily, no; all of these descriptions were copied from the Pamphlet of one or another of those 6 quadrangles!

**Comment by brandon-rhodes** [comment]
(Let me know if any more information would be helpful before merging this pull request! It's fine if you're just busy; I am too.)

**Comment by rclark** [comment]
Hi @brandon-rhodes -- sorry for the delay. I've been out on vacation for several weeks spending some time near but not in this geologic map :)

This steps I have to take are to merge your changes, then push through some data updates and uploads before they'll show up. I should be able to tackle it this weekend.

As always, thank you for putting in the effort!

**Comment by brandon-rhodes** [comment]
Thanks for the update! I’ve been busy as well. It will be fun to see the new descriptions show up.

**Comment by brandon-rhodes** [comment]
Running back across this PR after a few months, I thought I'd double-check whether there were any tweaks you needed me to make for the new strata descriptions to be correct. Thanks!

**Comment by rclark** [comment]
Phew new job, new responsibilities, and all this lockdown. Sorry for such a long delay, I'm going to see about getting this updated in the next week!!

**Comment by brandon-rhodes** [comment]
WOOHOO! Thank you for accepting my contribution, I look forward to seeing the descriptions when I mouse over these formations.

**Comment by rclark** [comment]
Screen Shot 2022-05-20 at 9 56 46 AM

It's live!

**Pull request merged**
